/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;

/**
 *
 * @author shrajnashetty
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeComboBox = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        FemaleRadioButton = new javax.swing.JRadioButton();
        MaleRadioButton = new javax.swing.JRadioButton();
        PreferNotRadioButton = new javax.swing.JRadioButton();
        SubmitButton = new javax.swing.JButton();
        AgeTextField = new javax.swing.JTextField();
        PrefixLabel = new javax.swing.JLabel();
        PrefixComboBox = new javax.swing.JComboBox<>();
        MessageLabel = new javax.swing.JLabel();
        MessageScrollPanel = new javax.swing.JScrollPane();
        MessageTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));

        TitleLabel.setFont(new java.awt.Font("AppleMyungjo", 3, 24)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("CUSTOMER REGISTRATION FORM");

        FirstNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        FirstNameLabel.setText("First Name :");

        LastNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name :");

        AgeComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        AgeComboBox.setText("Age :");

        EmailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EmailLabel.setText("Email :");

        GenderLabel.setText("Gender :");

        FirstNameTextField.setToolTipText("");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        GenderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setActionCommand("FEMALE");

        GenderButtonGroup.add(MaleRadioButton);
        MaleRadioButton.setText("Male");
        MaleRadioButton.setActionCommand("MALE");

        GenderButtonGroup.add(PreferNotRadioButton);
        PreferNotRadioButton.setText("Prefer not to say");
        PreferNotRadioButton.setActionCommand("NOT SPECIFIED");

        SubmitButton.setBackground(new java.awt.Color(153, 204, 255));
        SubmitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        PrefixLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PrefixLabel.setText("Prefix :");

        PrefixComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miss.", "Ms.", "Mrs.", "Mr.", " " }));
        PrefixComboBox.setSelectedIndex(-1);

        MessageLabel.setText("Message :");

        MessageTextArea.setColumns(20);
        MessageTextArea.setRows(5);
        MessageScrollPanel.setViewportView(MessageTextArea);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addComponent(LastNameLabel)
                            .addComponent(AgeComboBox)
                            .addComponent(EmailLabel)
                            .addComponent(GenderLabel)
                            .addComponent(PrefixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MessageLabel))
                        .addGap(165, 165, 165)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(MaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(PreferNotRadioButton))
                            .addComponent(PrefixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MessageScrollPanel)
                            .addComponent(EmailTextField)
                            .addComponent(LastNameTextField)
                            .addComponent(FirstNameTextField)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrefixLabel)
                    .addComponent(PrefixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeComboBox)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton)
                    .addComponent(PreferNotRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel)
                    .addComponent(MessageScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        
        //to ensure prefix doesn't take NULL value
        String prefix = PrefixComboBox.getSelectedItem() != null ? PrefixComboBox.getSelectedItem().toString() : "";
        if (prefix.isEmpty() || prefix.equals(" ")) {
            JOptionPane.showMessageDialog(this, "Please select a Prefix.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String firstName = FirstNameTextField.getText();
        if (firstName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a First Name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String lastName = LastNameTextField.getText();
        if (lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Last Name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String age = AgeTextField.getText();
        if (age.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an Age.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int age_int = Integer.parseInt(age);
            if (age_int < 0 || age_int > 120) {
                JOptionPane.showMessageDialog(this, "Age must be between 0 and 120.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a valid number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String email = EmailTextField.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
    if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this, "Invalid email address.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    return; 
    }
        //to ensure gender doesn't take NULL value
        String gender = GenderButtonGroup.getSelection() != null ? GenderButtonGroup.getSelection().getActionCommand() : "";
        if (!MaleRadioButton.isSelected() && !FemaleRadioButton.isSelected() && !PreferNotRadioButton.isSelected()) {
    JOptionPane.showMessageDialog(this, "Please select a gender.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    return;
        }
        
        String message = MessageTextArea.getText();
        int maxMessageLength = 200; // Set your desired maximum message length here
    if (message.length() > maxMessageLength) {
        JOptionPane.showMessageDialog(this, "Message should not exceed " + maxMessageLength + " characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
        //if (prefix.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || age.isEmpty() || email.isEmpty() || gender.isEmpty()) {
        //JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    //} else {
        JOptionPane.showMessageDialog(this, prefix + " " + firstName + " " + lastName + " of age " + age + " years, emailid - " + email + " and gender - "+gender+" has successfully registered with us!\nFollowing is the message from the Customer:\n"+message, "Customer Registration Form", JOptionPane.PLAIN_MESSAGE);
        //}
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeComboBox;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JScrollPane MessageScrollPanel;
    private javax.swing.JTextArea MessageTextArea;
    private javax.swing.JRadioButton PreferNotRadioButton;
    private javax.swing.JComboBox<String> PrefixComboBox;
    private javax.swing.JLabel PrefixLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
